CREATE DATABASE IF NOT EXISTS critterpedia;
USE critterpedia;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_fish;
DROP TABLE IF EXISTS user_bugs;

CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(50),
    email VARCHAR(50),
    password VARCHAR(256)
);

CREATE TABLE user_fish (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user INT UNSIGNED,
    fish INT UNSIGNED,
	favorited BOOLEAN DEFAULT 0,
	catched BOOLEAN DEFAULT 0
);

CREATE TABLE user_bugs (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user INT UNSIGNED,
    bug INT UNSIGNED,
	favorited BOOLEAN DEFAULT 0,
	catched BOOLEAN DEFAULT 0
);