USE DATABASE critterpedia;

INSERT INTO shadow_sizes (size) VALUES
    ("Narrow"),
    ("X-Small"),
    ("Small"),
    ("Medium"),
    ("Large"),
    ("X Large"),
    ("Largest"),
    ("Largest (Fin)");

INSERT INTO locations (location) VALUES
    ("Pond"),
    ("River"),
    ("Rivermouth"),
    ("Clifftop river"),
    ("Sea"),
    ("Flying"),
    ("Flying near black, blue, or purple flowers"),
    ("Flying near purple flowers"),
    ("Near lights"),
    ("On trees"),
    ("On the ground"),
    ("On flowers"),
    ("On white flowers"),
    ("Near flowers"),
    ("In trees"),
    ("Underground"),
    ("On ponds and rivers"),
    ("On tree stumps"),
    ("On the ground (rolling snowballs)"),
    ("On palm trees"),
    ("Under trees"),
    ("On Spoiled turnips"),
    ("On the beach"),
    ("On beach rocks"),
    ("Near trash"),
    ("On villagers"),
    ("On rocks and bushes (when raining or snowing)"),
    ("Under rocks");

INSERT INTO rarities (rarity) VALUES
    ("Extremely Common (200%)"),
    ("Very Common (80%)"),
    ("Very Common (70%)"),
    ("Very Common (60%)"),
    ("Common (50%)"),
    ("Common (40%)"),
    ("Common (35%)"),
    ("Common (-)"),
    ("Uncommon (30%)"),
    ("Uncommon (25%)"),
    ("Uncommon (20%)"),
    ("Very Uncommon (15%)"),
    ("Very Uncommon (10%)"),
    ("Rare/Very Uncommon (5% Jun-Aug North, 10% Dec-Feb South)"),
    ("Rare (7%)"),
    ("Rare (5%)"),
    ("Very Rare (3%)"),
    ("Very Rare (2%)"),
    ("Ultra Rare (1%)"),
    ("5 per day (-)");

INSERT INTO time_of_days (start, end) VALUES
    ("04:00:00", "19:00:00"),
    ("08:00:00", "17:00:00"),
    ("08:00:00", "19:00:00"),
    ("09:00:00", "16:00:00"),
    ("16:00:00", "09:00:00"),
    ("17:00:00", "04:00:00"),
    ("17:00:00", "08:00:00"),
    ("19:00:00", "04:00:00"),
    ("19:00:00", "08:00:00"),
    ("21:00:00", "04:00:00"),
    ("22:00:00", "04:00:00"),
    ("22:00:00", "08:00:00"),
    ("00:00:00", "24:00:00");

INSERT INTO fish (name, description, time_of_year_north_start, time_of_year_north_end, time_of_year_south_start, time_of_year_south_end, time_of_day_start, time_of_day_end, location, shadow_size, price_nooks_cranny, )
    (
        "Bitterling",
        "I caught a bitterling! It's mad at me, but only a little.",
        11,
        3,
        4,
        9,
        12,
        2,
        2,
        900,
        1350
    ), (
        "Pale Chub",
        "I caught a pale chub! That name seems a bit judgy...",
        1,
        12,
        1,
        12,
        4,
        2,
        2,
        200,
        300
    ), (
        "Crucian Carp",
        "I caught a crucian carp! My skills are sharp!",
        1,
        12,
        1,
        12,
        12,
        2,
        3,
        160,
        240
    ), (
        "Dace",
        "I caught a dace! Hope I have some space!",
        1,
        12,
        1,
        12,
        5,
        2,
        4,
        240,
        360
    ), (
        "Carp",
        "I caught a carp! If I catch another, they can carpool!",
        1,
        12,
        1,
        12,
        12,
        1,
        5,
        300,
        450
    ), (
        "Koi",
        "I caught a koi! I don't know why it's so shy... or such a bad speller...",
        1,
        12,
        1,
        12,
        5,
        1,
        5,
        4000,
        6000
    ), (
        "Goldfish",
        "I caught a goldfish! It's worth its weight in fish!",
        1,
        12,
        1,
        12,
        12,
        1,
        2,
        1300,
        1950
    ), (
        "Pop-Eyed Goldfish",
        "I caught a pop-eyed goldfish! It looks so...surprised!",
        1,
        12,
        1,
        12,
        4
        1,
        2,
        1300,
        1950
    ),(
        "Ranchu Goldfish",
        "I caught a Ranchu Goldfish! But I prefer balsamicu goldfish!",
        1,
        12,
        1,
        12,
        4
        1,
        3,
        4500,
        6750
    ), (
        "Killifish",
        "I caught a killifish! The streams are safe again",
        4,
        8,
        10,
        2,
        12,
        1,
        2,
        300,
        450
    ), (
        "Crawfish",
        "I caught a crawfish! Or else it's a lobster and I'm a giant!",
        4,
        9,
        10,
        3,
        12,
        1,
        3,
        200,
        300
    ), (
        "Soft-Shelled Turtle",
        "I caught a soft-shelled turtle! It's more sensitive than other turtles.",
        8,
        9,
        2,
        3,
        5,
        2,
        5,
        3750,
        5625
    ), (
        "Snapping Turtle",
        "I caught a snapping turtle! How can it snap without fingers?",
        4,
        10,
        10,
        4,
        9,
        2,
        5,
        5000,
        7500
    ), (
        "Tadpole",
        "I caught a tadpole... It's just a tad small.",
        3,
        7,
        9,
        1,
        12,
        1,
        2,
        100,
        150
    ), (
        "Frog",
        "I caught a frog! Or it's a new neighbor... and I have some apologizing to do",
        5,
        8,
        11,
        2,
        12,
        1,
        3,
        120,
        180
    ), (
        "Freshwater Goby",
        "I caught a freshwater goby! Time to go bye-bye!",
        1,
        12,
        1,
        12,
        5,
        2,
        3,
        400,
        600
    ), (
        "Loach",
        "I caught a loach! It's...looking at me with reproach.",
        3,
        5,
        9,
        11,
        12,
        2,
        3,
        400,
        600
    ), (
        "Catfish",
        "I caught a catfish! I'm more of a dogfish person...",
        5,
        10,
        11,
        4,
        5,
        1,
        5,
        800,
        1200
    ), (
        "Giant Snakehead",
        "I caugh a giant snakehead! Um...but I asked for a medium?",
        6,
        8,
        12,
        2,
        4,
        1,
        5,
        5500,
        8250
    ), (
        "Bluegill",
        "I caught a bluegill! Do you think it calls me 'pinklung'?",
        1,
        12,
        1,
        12,
        4,
        2,
        3,
        180,
        270
    ),