USE DATABASE critterpedia;

INSERT INTO shadow_sizes (size) VALUES
    ("Narrow"),
    ("Smallest"),
    ("Small"),
    ("Medium"),
    ("Large"),
    ("X Large"),
    ("Largest"),
    ("Largest (Fin)");

INSERT INTO locations (location) VALUES
    ("Pond"),
    ("River"),
    ("Rivermouth"),
    ("Clifftop river"),
    ("Sea"),
    ("Flying"),
    ("Flying near black, blue, or purple flowers"),
    ("Flying near purple flowers"),
    ("Near lights"),
    ("On trees"),
    ("On the ground"),
    ("On flowers"),
    ("On white flowers"),
    ("Near flowers"),
    ("In trees"),
    ("Underground"),
    ("On ponds and rivers"),
    ("On tree stumps"),
    ("On the ground (rolling snowballs)"),
    ("On palm trees"),
    ("Under trees"),
    ("On Spoiled turnips"),
    ("On the beach"),
    ("On beach rocks"),
    ("Near trash"),
    ("On villagers"),
    ("On rocks and bushes (when raining or snowing)"),
    ("Under rocks");

INSERT INTO rarities (rarity) VALUES
    ("Extremely Common (200%)"),
    ("Very Common (80%)"),
    ("Very Common (70%)"),
    ("Very Common (60%)"),
    ("Common (50%)"),
    ("Common (40%)"),
    ("Common (35%)"),
    ("Common (-)"),
    ("Uncommon (30%)"),
    ("Uncommon (25%)"),
    ("Uncommon (20%)"),
    ("Very Uncommon (15%)"),
    ("Very Uncommon (10%)"),
    ("Rare/Very Uncommon (5% Jun-Aug North, 10% Dec-Feb South)"),
    ("Rare (7%)"),
    ("Rare (5%)"),
    ("Very Rare (3%)"),
    ("Very Rare (2%)"),
    ("Ultra Rare (1%)"),
    ("5 per day (-)");